### ISSUE TITLE
Wording in introduction - suggested re-write

### ISSUE THREAD

**Issue by deafeningraisins** [data-lessons/library-webscraping#23]
In its simplest form, this can be achieved by copying and pasting snippets from a web page, but this can be unpractical if there is a large amount of data to be extracted, or if it spread over a large number of pages. 

Replace "unpractical" with "impractical".  Unpractical is rarely used, though correct.
Change: "or if it spread" with "or if it is spread". 

Automating web scraping also allows to define whether the process should be run at regular intervals and capture changes in the data.

Change "also allows" to "also allows you".

**Comment by ldko** [comment]
Hi @deafeningraisins I have a PR #22 open that fixes the "if it spread" and makes a change to the sentence with "allows to define". I also considered replacing "unpractical" with "impractical" but didn't, since I wasn't sure if "unpractical" is often used in places. I will add that change to the PR, since you also noticed it.

**Comment by ldko** [comment]
Hi @deafeningraisins I have a PR open that fixes the "if it spread" and makes a change to the sentence with "allows to define"
